# Generated by Django 4.0 on 2022-01-07 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinfo',
            name='authors',
            field=models.CharField(default='', max_length=200),
        ),
    ]
